### ISSUE TITLE
В python 3.7 не читаются si-card 5

### ISSUE THREAD

**Issue by kbats183** [sportorg/pysport#314]
Независимо от версии выводится ошибка:
ERROR 2019-01-07 11:43:59,194 Dummy-4@sireader.py:58 No card in the device.
ERROR 2019-01-07 11:44:13,966 Dummy-4@sireader.py:65 generator raised StopIteration
Traceback (most recent call last):
  File "C:\Users\maker\Desktop\pysport-dev\sportorg\libs\sireader\sireader.py", line 673, in twochars
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maker\Desktop\pysport-dev\sportorg\modules\sportident\sireader.py", line 53, in run
    card_data = si.read_sicard()
  File "C:\Users\maker\Desktop\pysport-dev\sportorg\libs\sireader\sireader.py", line 1100, in read_sicard
    b'')[1]
  File "C:\Users\maker\Desktop\pysport-dev\sportorg\libs\sireader\sireader.py", line 920, in _send_command
    crc = SIReader._crc(command_string)
  File "C:\Users\maker\Desktop\pysport-dev\sportorg\libs\sireader\sireader.py", line 689, in _crc
    for c in twochars(s[2:]):
RuntimeError: generator raised StopIteration

**Comment by daxartio** [comment]
Sireader точно наш? Мы его теперь храним в отдельной репе @sportorg/sireader

**Comment by kbats183** [comment]
Да. В 1.2.0 та же ошибка

**Comment by daxartio** [comment]
Python 3.7 - новая версия питона. Думаю скоро исправим

**Comment by daxartio** [comment]
https://www.python.org/dev/peps/pep-0479/

**Comment by daxartio** [comment]
https://github.com/sportorg/sireader/commit/c975b8c27639371c193570b1a4c57565d25e7af6
