### ISSUE TITLE
Запуск приложения с использованием poetry

### ISSUE THREAD

**Issue by Phylosof** [sportorg/pysport#388]
Проинсталировал зависимости через poetry install, но при попытке запуска приложения, приложение не находит установленные зависимости. Какова последовательность действия для запуска, какие есть подводные камни?
`Traceback (most recent call last):
  File "SportOrg.pyw", line 2, in <module>
    from sportorg.gui.main import Application
  File "C:\pysport-develop\sportorg\gui\main.py", line 5, in <module>
    from PySide2.QtWidgets import QApplication
ModuleNotFoundError: No module named 'PySide2'`

**Comment by Phylosof** [comment]
По-видимому запускать надо через команду `python sportorg` а не `python SportOrg.pyw` но тогда выдает сообщение `C:\Users\Technic\AppData\Local\pypoetry\Cache\virtualenvs\sportorg-QsfJ-E1i-py3.8\Scripts\python.exe: can't find '__main__' module in 'sportorg'`

**Comment by daxartio** [comment]
Добрый день. Да есть такая фича. Poetry создаёт окружение если его нет. Можно запустить командой `poetry run python SportOrg.pyw`

**Comment by daxartio** [comment]
Сегодня поправлю ридми файл

**Comment by Phylosof** [comment]
Выдает ошибку:
`C:\pysport-develop> poetry run python SportOrg.pyw
Traceback (most recent call last):
  File "SportOrg.pyw", line 2, in <module>
    from sportorg.gui.main import Application
  File "C:\pysport-develop\sportorg\gui\main.py", line 10, in <module>
    from sportorg.gui.main_window import MainWindow
  File "C:\pysport-develop\sportorg\gui\main_window.py", line 11, in <module>
    from sportorg.gui.dialogs.course_edit import CourseEditDialog
  File "C:\pysport-develop\sportorg\gui\dialogs\course_edit.py", line 3, in <module>
    from sportorg.gui.dialogs.dialog import BaseDialog, LineField, NumberField, TextField
  File "C:\pysport-develop\sportorg\gui\dialogs\dialog.py", line 24, in <module>
    from sportorg.gui.utils.custom_controls import AdvComboBox
  File "C:\pysport-develop\sportorg\gui\utils\custom_controls.py", line 5, in <module>
    from sportorg.language import translate
  File "C:\pysport-develop\sportorg\language.py", line 57, in <module>
    translate = locale()
  File "C:\pysport-develop\sportorg\language.py", line 39, in locale
    cat = gettext.Catalog(
  File "c:\users\technic\appdata\local\programs\python\python38-32\lib\gettext.py", line 588, in translation
    raise FileNotFoundError(ENOENT,
FileNotFoundError: [Errno 2] No translation file found for domain: 'sportorg'`

**Comment by daxartio** [comment]
Кажется надо добавить `.env` файл и передать туда `DEBUG=True`

**Comment by Phylosof** [comment]
Благодарю, запустилось :-)

**Comment by Phylosof** [comment]
Как оказалось, запускается только под Linux. На Windows выдает ошибку 
Traceback (most recent call last):
  File "SportOrg.pyw", line 2, in <module>
    from sportorg.gui.main import Application
  File "C:\pysport-develop\sportorg\gui\main.py", line 10, in <module>
    from sportorg.gui.main_window import MainWindow
  File "C:\pysport-develop\sportorg\gui\main_window.py", line 41, in <module>
    from sportorg.modules.printing.model import (
  File "C:\pysport-develop\sportorg\modules\printing\model.py", line 10, in <module>
    from sportorg.modules.printing.printout_split import SportorgPrinter
  File "C:\pysport-develop\sportorg\modules\printing\printout_split.py", line 8, in <module>
    from pywin32 import win32con
ModuleNotFoundError: No module named 'pywin32'

**Comment by Phylosof** [comment]
> Как оказалось, запускается только под Linux. На Windows выдает ошибку
> Traceback (most recent call last):
> File "SportOrg.pyw", line 2, in
> from sportorg.gui.main import Application
> File "C:\pysport-develop\sportorg\gui\main.py", line 10, in
> from sportorg.gui.main_window import MainWindow
> File "C:\pysport-develop\sportorg\gui\main_window.py", line 41, in
> from sportorg.modules.printing.model import (
> File "C:\pysport-develop\sportorg\modules\printing\model.py", line 10, in
> from sportorg.modules.printing.printout_split import SportorgPrinter
> File "C:\pysport-develop\sportorg\modules\printing\printout_split.py", line 8, in
> from pywin32 import win32con
> ModuleNotFoundError: No module named 'pywin32'

Все разрешилось переустановкой пакета из poetry
